worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    client_max_body_size 20M;

    server {
        listen 8888;
        root /var/www/heimdall/public;
        index index.php index.html;

        disable_symlinks off;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location /storage {
            alias /share/heimdall/storage/app/public;
            try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        location ~ /\.ht {
            deny all;
        }
    }
}
